---
name: Robustness
on: [pull_request]
permissions: read-all
jobs:
  main:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 12
      testTimeout: 30m
      artifactName: main
      runs-on: "['ubuntu-latest-8-cores']"
  main-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 12
      testTimeout: 30m
      artifactName: main-arm64
      runs-on: "['actuated-arm64-8cpu-8gb']"
