---
name: Tests
on: [push, pull_request]
permissions: read-all
jobs:
  amd64:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: amd64
      runs-on: ubuntu-latest
  amd64-macos:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: amd64
      runs-on: macos-latest
  arm64:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: arm64
      runs-on: actuated-arm64-8cpu-8gb
