---
name: Tests
on: [push, pull_request]
permissions: read-all
jobs:
  amd64:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: amd64
      runs-on: ubuntu-latest
  arm64:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: arm64
      runs-on: actuated-arm64-8cpu-8gb

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - id: goversion
      run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: ${{ steps.goversion.outputs.goversion }}
    - env:
      run: |
        set -euo pipefail
        go clean -testcache
        make test-unit
    - uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
      if: always()
      with:
        name: "macos"
        path: ./**/junit_*.xml